const express = require('express');
const crypto = require('crypto');
const { dbRun, dbGet } = require('./db.js');

const router = express.Router();

function getHash(content) {
  return crypto.createHash('sha256').update(content).digest('hex');
}

// Authentication Routes
router.post('/auth/signup', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });

    // Hash the password for basic security (in production use bcrypt)
    const passwordHash = getHash(password);

    // Check if user exists
    const existingUser = await dbGet('SELECT * FROM users WHERE email = ?', [email]);
    if (existingUser) {
      return res.status(400).json({ error: 'Email already in use' });
    }

    await dbRun('INSERT INTO users (email, password) VALUES (?, ?)', [email, passwordHash]);
    const newUser = await dbGet('SELECT id, email, createdAt FROM users WHERE email = ?', [email]);
    
    // Auto-login after signup by returning user info
    res.json({ success: true, user: newUser });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Internal server error during signup' });
  }
});

router.post('/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'Email and password are required' });

    const passwordHash = getHash(password);
    
    const user = await dbGet('SELECT id, email, createdAt FROM users WHERE email = ? AND password = ?', [email, passwordHash]);
    
    if (user) {
      res.json({ success: true, user });
    } else {
      res.status(401).json({ error: 'Invalid email or password' });
    }
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Internal server error during login' });
  }
});

const fetch = require('node-fetch');

// Module B: AI Probability Check (API implementation)
async function getAIProbability(content) {
  if (!content || content.trim().length === 0) return 0.5;

  // Hardcoded check requested by the user
  const hardcodedAiString = "Discipline shapes dreams into achievable goals.\nFocus turns distractions into determination.\nEffort compounds into unstoppable momentum.\nGrowth begins the moment you refuse to quit.";
  if (content.trim() === hardcodedAiString.trim()) {
    console.log("Hardcoded AI string detected. Forcing high AI probability.");
    return 0.95; // 95% AI Probability will result in a trust score of ~5
  }

  // Retrieve API configured through environment variables
  // By default, try OpenRouter, then OpenAI
  const apiKey = process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY;
  const apiEndpoint = process.env.OPENROUTER_API_KEY 
    ? 'https://openrouter.ai/api/v1/chat/completions' 
    : 'https://api.openai.com/v1/chat/completions';
  
  const model = process.env.OPENROUTER_API_KEY 
    ? (process.env.AI_MODEL || 'meta-llama/llama-3-8b-instruct:free')
    : (process.env.AI_MODEL || 'gpt-3.5-turbo');

  // If no API key is provided, gracefully fallback to the heuristic method
  if (!apiKey) {
    console.warn("No OPENROUTER_API_KEY or OPENAI_API_KEY found. Falling back to heuristic AI detection.");
    return executeHeuristicFallback(content);
  }

  try {
    const response = await fetch(apiEndpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        ...(process.env.OPENROUTER_API_KEY && {
          'HTTP-Referer': 'http://localhost:5173', // Required by OpenRouter
          'X-Title': 'VeritasID'
        })
      },
      body: JSON.stringify({
        model: model,
        messages: [
          {
            role: "system",
            content: "You are an expert AI text detector. Analyze the following text and determine the probability that it was generated by an AI. Return ONLY a single floating-point number between 0.0 and 1.0, where 0.0 means it is definitely human-written, and 1.0 means it is definitely AI-generated. Do not include any other text, explanation, or markdown formatting."
          },
          {
            role: "user",
            content: content
          }
        ],
        temperature: 0.1, // Low temperature for consistent scoring
      })
    });

    if (!response.ok) {
      console.error(`AI API Error: ${response.status} ${response.statusText}`);
      const text = await response.text();
      console.error(text);
      return executeHeuristicFallback(content);
    }

    const data = await response.json();
    const resultText = data.choices[0].message.content.trim();
    
    // Parse the float from the API response robustly
    let probability;
    const match = resultText.match(/0?\.\d+|[01]/);
    
    if (match) {
      probability = parseFloat(match[0]);
    } else {
      console.warn(`AI API returned invalid format without numbers: '${resultText}'. Falling back to heuristic.`);
      return executeHeuristicFallback(content);
    }
    
    if (isNaN(probability) || probability < 0 || probability > 1) {
      console.warn(`AI API returned out of bounds probabilty: '${probability}'. Falling back to heuristic.`);
      return executeHeuristicFallback(content);
    }
    
    return probability;

  } catch (error) {
    console.error("Failed to connect to AI API. Falling back to heuristic.", error);
    return executeHeuristicFallback(content);
  }
}

// Fallback heuristic method
function executeHeuristicFallback(content) {
  const text = content.toLowerCase();
  
  // 1. Keyword Usage (Common LLM transitional phrases and vocabulary)
  const aiKeywords = [
    "delve", "tapestry", "multifaceted", "in conclusion", "it is important to note",
    "furthermore", "moreover", "testament to", "underscore", "crucial", "vital",
    "intricate", "navigate", "realm", "landscape", "foster", "transformative",
    "paramount", "evolving", "paradigm", "revolutionize"
  ];
  
  let keywordMatches = 0;
  aiKeywords.forEach(word => {
    const regex = new RegExp(`\\b${word}\\b`, 'g');
    const matches = text.match(regex);
    if (matches) keywordMatches += matches.length;
  });

  // Significantly increase score for each keyword match
  let aiScore = Math.min((keywordMatches * 0.25), 0.85);

  // 2. Sentence variance (Burstiness proxy)
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
  
  if (sentences.length > 2) {
    const lengths = sentences.map(s => s.trim().split(/\s+/).length);
    const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
    const variance = lengths.reduce((acc, len) => acc + Math.pow(len - mean, 2), 0) / lengths.length;
    
    // Low variance (all sentences similar length) is highly indicative of typical LLM generation
    if (variance < 20) {
        aiScore += 0.25;
    } else if (variance > 40) {
        aiScore -= 0.15;
    }
  } else if (keywordMatches > 2) {
      // If it's short but full of keywords, penalize heavily
      aiScore += 0.4;
  } else {
     aiScore = 0.3 + (Math.random() * 0.2);
  }

  return Math.max(0.05, Math.min(aiScore, 0.99));
}

// Module C: Trust Score Algorithm
function calculateTrustScore(aiProbability, isNewHash) {
  // If aiProbability is high (e.g., > 0.8), rapidly decay the trust score
  // We apply an exponential curve so even a 0.8 AI Probability gives a trust score around ~20-30 max.
  let baseScore = Math.pow(1 - aiProbability, 1.5) * 100;
  
  // 2. Structural Consistency acts as a minor multiplier/penalty (+/- 5%)
  // (We use a mock heuristic score that typically yields > 80%)
  const structuralConsistency = 0.8 + Math.random() * 0.2;
  const structuralAdjustment = (structuralConsistency - 0.9) * 10; // slightly penalize or boost

  // 3. Origin verification acts as a minor flat bonus
  const originBonus = isNewHash ? 0 : -5;
  
  // Final calculation
  let finalScore = baseScore + structuralAdjustment + originBonus;
  
  // Clamp between 0 and 100
  return Math.floor(Math.max(0, Math.min(100, finalScore)));
}

// Module A: The Intake Engine -> Generate
router.post('/generate', async (req, res) => {
  try {
    const { content } = req.body;
    if (!content) return res.status(400).json({ error: 'Content is required' });

    const hash = getHash(content);
    
    // Check if already certified
    const existing = await dbGet('SELECT * FROM passports WHERE hash = ?', [hash]);
    if (existing) {
      return res.json({ success: true, certificate: existing });
    }

    const aiProbability = await getAIProbability(content);
    const structConst = 0.9;
    const originVer = 1.0;
    const trustScore = calculateTrustScore(aiProbability, true);
    
    const contentId = `VID-${Date.now()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
    const timestamp = new Date().toISOString();

    await dbRun(
      'INSERT INTO passports (contentId, hash, content, trustScore, aiProbability, structuralConsistency, originVerification, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
      [contentId, hash, content, trustScore, aiProbability, structConst, originVer, timestamp]
    );

    const certificate = await dbGet('SELECT * FROM passports WHERE hash = ?', [hash]);
    res.json({ success: true, certificate });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Internal server error while generating ID' });
  }
});

// Module D: The Public Passport -> Verify
router.post('/verify', async (req, res) => {
  try {
    const { content } = req.body;
    if (!content) return res.status(400).json({ error: 'Content is required' });

    const originalHash = getHash(content);
    
    const existing = await dbGet('SELECT * FROM passports WHERE hash = ?', [originalHash]);
    
    if (existing) {
      // Perfect match means 100% cryptographic integrity
      return res.json({ 
        status: 'authentic',
        certificate: existing
      });
    }

    // Fallback if hash did not match exactly. In VeritasID MVP, even a comma change flags as modified.
    res.json({
      status: 'modified',
      modifications: [
        "Cryptographic hash mismatch. Content has been altered or never certified."
      ],
      certificate: null
    });
    
  } catch (error) {
    res.status(500).json({ error: 'Internal server error while verifying ID' });
  }
});

module.exports = router;
